# Generated by Django 3.1 on 2021-01-11 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0069_section_page'),
        ('account', '0004_remove_account_primary_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='primary_portfolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfolio'),
        ),
    ]
