# Generated by Django 3.1 on 2021-01-09 00:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0051_auto_20201223_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
