# Generated by Django 3.1 on 2021-01-09 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0053_auto_20210109_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['index']},
        ),
        migrations.RenameField(
            model_name='link',
            old_name='number',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='number',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='number',
            new_name='index',
        ),
        migrations.AddField(
            model_name='page',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
