# Generated by Django 3.1 on 2021-01-09 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0054_auto_20210109_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
