# Generated by Django 3.1 on 2021-01-09 00:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0056_auto_20210109_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='link',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
