# Generated by Django 3.1 on 2021-01-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0057_auto_20210109_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
    ]
