# Generated by Django 3.1 on 2021-01-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0058_remove_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
