# Generated by Django 3.1 on 2021-01-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0061_auto_20210111_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='uuid',
            new_name='id',
        ),
    ]
