# Generated by Django 3.1 on 2021-01-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0063_auto_20210111_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='uuid',
            new_name='id',
        ),
    ]
