# Generated by Django 3.1 on 2021-01-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0065_auto_20210111_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='page',
            name='portfolio',
        ),
    ]
