# Generated by Django 3.1 on 2021-01-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0066_auto_20210111_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='portfolio',
            field=models.ForeignKey(default='9e9f0554-9cfe-40fd-abcb-5aef0517a0b0', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='portfolio.portfolio'),
            preserve_default=False,
        ),
    ]
