# Generated by Django 3.1 on 2021-01-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0067_page_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='page',
        ),
    ]
