# Generated by Django 3.1 on 2021-01-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0069_section_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='uuid',
            new_name='id',
        ),
        migrations.CreateModel(
            name='SectionLink',
            fields=[
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio.link')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.section')),
            ],
        ),
    ]
