# Generated by Django 3.1 on 2021-01-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0070_auto_20210111_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='owner',
        ),
    ]
