# Generated by Django 3.1 on 2021-01-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0071_remove_link_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioLink',
            fields=[
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portfolio.link')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.portfolio')),
            ],
        ),
    ]
