# Generated by Django 3.1 on 2021-01-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0073_auto_20210113_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uuid',
            new_name='id',
        ),
    ]
