# Generated by Django 3.1 on 2021-01-16 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0074_auto_20210113_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionlink',
            name='link',
        ),
        migrations.AddField(
            model_name='sectionlink',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sectionlink',
            name='icon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sectionlink',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='sectionlink',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sectionlink',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
