# Generated by Django 3.1 on 2021-01-16 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0075_auto_20210116_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliolink',
            name='link',
        ),
        migrations.AddField(
            model_name='portfoliolink',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliolink',
            name='icon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliolink',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='portfoliolink',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfoliolink',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
