# Generated by Django 3.1 on 2021-01-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0076_auto_20210116_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliolink',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sectionlink',
            name='title',
        ),
        migrations.AddField(
            model_name='portfoliolink',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sectionlink',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
