# Generated by Django 3.1 on 2021-01-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0077_auto_20210116_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
