# Generated by Django 3.1 on 2021-01-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0078_auto_20210118_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
