# Generated by Django 3.1 on 2021-01-18 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0079_auto_20210118_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portfolio.image'),
        ),
    ]
