# Generated by Django 3.1 on 2021-01-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0081_section_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='border',
            field=models.BooleanField(default=False),
        ),
    ]
