# Generated by Django 3.1 on 2021-01-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0082_section_border'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
