# Generated by Django 3.1.7 on 2021-03-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0083_auto_20210125_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profile_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='portfolio.image'),
        ),
    ]
