# Generated by Django 3.1.7 on 2021-03-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0085_auto_20210306_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_avatars', to='portfolio.image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_backgrounds', to='portfolio.image'),
        ),
    ]
