# Generated by Django 3.1.7 on 2021-03-08 09:24

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0086_auto_20210307_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path_40_square',
            field=models.ImageField(null=True, upload_to=portfolio.models.Image.image_path),
        ),
    ]
